setl bg=dark
setl nonumber
setl laststatus=0
setl colorcolumn=
setl guifont=Menlo:h24
setl wrap
setl linebreak
setl nolist
setl textwidth=0
setl wrapmargin=0
setl noautoindent
setl nocindent
setl nosmartindent
setl so=999
setl vb
setl t_vb=
